language: groovy

jdk:
  - openjdk11

install: true

env:
  - TERM=dumb

script:
  - ./gradlew getRuntime
  - ./gradlew load
  - ./gradlew test --info

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
