language: groovy

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: true

env:
  - TERM=dumb

script:
  - gradle load
  - gradle test --info

cache:
  directories:
    - $HOME/.gradle/caches
