package ars.rockycube

import org.moqui.Moqui
import org.moqui.context.ExecutionContext
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import spock.lang.Shared
import spock.lang.Specification

class AutoGeneratedIdTester extends Specification {
    protected final static Logger logger = LoggerFactory.getLogger(AutoGeneratedIdTester.class)

    @Shared
    ExecutionContext ec

    def setupSpec() {
        // set other conf - this configuration contains definition of Closure-related entities
        System.setProperty("moqui.conf", "../framework/src/test/resources/auto-generation/AutoGenConf.xml")

        // init the framework, get the ec
        ec = Moqui.getExecutionContext()
        ec.user.loginUser('john.doe', 'moqui')

        // disable authz
        this.ec.artifactExecution.disableAuthz()
    }

    def cleanupSpec() {
        if (ec) {
            // add some delay before turning off
            logger.info("Delaying deconstruction of ExecutionContext, for the purpose of storing data. Without this delay, the commit would have failed.")
            sleep(3000)

            // stop it all
            ec.destroy()
        }
    }

    def "test new item creation"() {
        when:
        // create record basic record
        def result1 = this.ec.service.sync().name("ars.rockycube.EndpointServices.create#EntityData")
                .disableAuthz()
                .parameters([
                        entityName: "ars.rockycube.test.Generated",
                        data: [description: 'whatever you like']
                ])
                .call()

        // create record with two keys
        def result2 = this.ec.service.sync().name("ars.rockycube.EndpointServices.create#EntityData")
                .disableAuthz()
                .parameters([
                        entityName: "ars.rockycube.test.GeneratedWithTwo",
                        data: [description: 'whenever you like']
                ])
                .call()

        then:
        result1.data.size() == 1
        result2.data.size() == 1
    }
}
