# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8.0
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get Dependancies
      run: |
        ./gradlew getRuntime
        ./gradlew downloadElasticSearch
        ./gradlew getComponent -Pcomponent=SimpleScreens
        ./gradlew getComponent -Pcomponent=HiveMind
        ./gradlew getComponent -Pcomponent=PopCommerce
        ./gradlew getComponent -Pcomponent=MarbleERP
        ./gradlew getComponent -Pcomponent=PopRestStore
        ./gradlew getComponent -Pcomponent=example        
    - name: Load, Save, and Test with Gradle
      run: ./gradlew loadsave test
    - name: Build and Run Moqui.war
      run: |
        ./gradlew build
        ls -la
        java -jar moqui.war
